"""URL map for the Eagle dashboard app."""

from django.urls import path, re_path

from . import (
    api, api_admin, api_admin_clients, api_admin_settings, api_admin_tools, api_admin_users, api_ai, api_attendance, api_clients, api_lead, api_mail, api_ops, api_sales, api_v1, spa, views,
    webhooks,
)

app_name = "dashboard"

urlpatterns = [
    # -- auth ---------------------------------------------------------------
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.home, name="home"),
    path("healthz", views.healthz, name="healthz"),

    # -- public legal pages (no login) --------------------------------------
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
    path("data-deletion/", views.data_deletion, name="data_deletion"),

    # -- operation ----------------------------------------------------------
    path("ops/inbox/", views.ops_inbox, name="ops_inbox"),
    path("ops/inbox/thread/<int:pk>/", views.ops_mail_thread, name="ops_mail_thread"),
    path("ops/chats/", views.ops_chats, name="ops_chats"),
    path("ops/chats/g/<int:room_id>/", views.ops_group_chat, name="ops_group_chat"),
    # Before the client-code route: "u" would otherwise read as a client code.
    path("ops/chats/u/<int:user_id>/", views.ops_staff_chat, name="ops_staff_chat"),
    path("ops/chats/<str:code>/", views.ops_chats, name="ops_chat_detail"),
    path("ops/tasks/", views.ops_tasks, name="ops_tasks"),
    path("ops/tasks/new/", views.ops_task_new, name="ops_task_new"),
    path("ops/team/", views.ops_team, name="ops_team"),

    # -- team leader / translator -------------------------------------------
    path("lead/", views.lead_home, name="lead_home"),
    path("lead/translators/", views.lead_translators, name="lead_translators"),
    path("translator/", views.translator_home, name="translator_home"),
    path("translator/payroll/", views.translator_payroll, name="translator_payroll"),

    # -- accounts -----------------------------------------------------------
    path("accounts/", views.accounts_overview, name="accounts_overview"),
    path("accounts/recalculate/", views.accounts_recalculate, name="accounts_recalculate"),
    path(
        "accounts/period/<int:pk>/approve/",
        views.accounts_period_approve,
        name="accounts_period_approve",
    ),
    path("accounts/line/<int:pk>/", views.accounts_line, name="accounts_line"),
    path(
        "accounts/line/<int:pk>/bonus/",
        views.accounts_line_bonus,
        name="accounts_line_bonus",
    ),
    path("accounts/attendance/", views.accounts_attendance, name="accounts_attendance"),
    path("accounts/violations/", views.accounts_violations, name="accounts_violations"),
    path(
        "accounts/violations/<int:pk>/<str:action>/",
        views.accounts_violation_decide,
        name="accounts_violation_decide",
    ),
    path("accounts/rules/", views.accounts_rules, name="accounts_rules"),
    path("accounts/rules/tier/", views.accounts_tier_add, name="accounts_tier_add"),
    path(
        "accounts/rules/tier/<int:pk>/delete/",
        views.accounts_tier_delete,
        name="accounts_tier_delete",
    ),
    path("accounts/salary/<int:pk>/", views.accounts_salary, name="accounts_salary"),

    # -- attendance: the person's own card ----------------------------------
    path("attendance/", views.my_attendance, name="my_attendance"),

    # -- attendance: HR -----------------------------------------------------
    path("hr/attendance/", views.hr_attendance, name="hr_attendance"),
    path("hr/attendance/<int:pk>/", views.hr_attendance_day, name="hr_attendance_day"),
    path(
        "hr/attendance/<int:pk>/clear/",
        views.hr_attendance_clear,
        name="hr_attendance_clear",
    ),
    path("hr/report/", views.hr_report, name="hr_report"),
    path("hr/schedules/", views.hr_schedules, name="hr_schedules"),
    path("hr/schedules/shift/<int:pk>/delete/", views.hr_shift_delete, name="hr_shift_delete"),
    path(
        "hr/schedules/override/<int:pk>/delete/",
        views.hr_override_delete,
        name="hr_override_delete",
    ),
    path("hr/schedules/template/", views.hr_template_add, name="hr_template_add"),
    path("hr/shifts/", views.hr_shifts, name="hr_shifts"),
    path(
        "hr/shifts/<int:pk>/delete/",
        views.hr_shift_template_delete,
        name="hr_shift_template_delete",
    ),
    path("hr/offices/", views.hr_offices, name="hr_offices"),
    path("hr/offices/<int:pk>/delete/", views.hr_office_delete, name="hr_office_delete"),
    path("hr/devices/", views.hr_devices, name="hr_devices"),
    path("hr/devices/<int:pk>/<str:action>/", views.hr_device_decide, name="hr_device_decide"),
    path("hr/overtime/", views.hr_overtime, name="hr_overtime"),
    path(
        "hr/overtime/<int:pk>/<str:action>/",
        views.hr_overtime_decide,
        name="hr_overtime_decide",
    ),

    # -- HR / recruitment ---------------------------------------------------
    path("hr/recruitment/", views.hr_recruitment, name="hr_recruitment"),
    path("hr/recruitment/settings/", views.hr_recruitment_settings, name="hr_recruitment_settings"),
    path("hr/vacancies/", views.hr_vacancies, name="hr_vacancies"),
    path("hr/vacancies/<str:code>/", views.hr_vacancy, name="hr_vacancy"),
    path(
        "hr/vacancies/question/<int:pk>/delete/",
        views.hr_vacancy_question_delete,
        name="hr_vacancy_question_delete",
    ),
    path("hr/questions/", views.hr_questions, name="hr_questions"),
    path("hr/departments/", views.hr_department_add, name="hr_department_add"),
    path("hr/candidates/", views.hr_candidates, name="hr_candidates"),
    path("hr/candidates/<str:code>/", views.hr_candidate, name="hr_candidate"),
    path("hr/candidates/<str:code>/hire/", views.hr_hire, name="hr_hire"),
    path("hr/interviews/<int:pk>/score/", views.hr_interview_score, name="hr_interview_score"),
    path("hr/tests/<int:pk>/score/", views.hr_test_score, name="hr_test_score"),
    path("reviewer/tests/", views.reviewer_tests, name="reviewer_tests"),
    path("hr/approvals/", views.hr_approvals, name="hr_approvals"),
    path(
        "hr/approvals/<str:code>/<str:action>/",
        views.hr_approval_decide,
        name="hr_approval_decide",
    ),
    path("hr/employees/", views.hr_employees, name="hr_employees"),
    path("hr/employees/<int:pk>/", views.hr_employee, name="hr_employee"),
    path("hr/employees/<int:pk>/shift/", views.hr_employee_shift, name="hr_employee_shift"),
    path(
        "hr/employees/<int:pk>/work-mode/",
        views.hr_employee_workmode,
        name="hr_employee_workmode",
    ),

    # -- leave, probation, performance, pay ---------------------------------
    path("leave/", views.my_leave, name="my_leave"),
    path("leave/<int:pk>/cancel/", views.leave_cancel, name="leave_cancel"),
    path("hr/leave/", views.hr_leave, name="hr_leave"),
    path("hr/leave/<int:pk>/<str:action>/", views.leave_decide, name="leave_decide"),
    path("hr/probation/", views.hr_probation, name="hr_probation"),
    path("hr/probation/<int:pk>/decide/", views.probation_decide, name="probation_decide"),
    path("hr/probation/open/<int:pk>/", views.probation_open, name="probation_open"),
    path("hr/performance/", views.hr_performance, name="hr_performance"),
    path("hr/complaints/", views.hr_complaints, name="hr_complaints"),
    path("hr/complaints/<int:pk>/resolve/", views.complaint_resolve, name="complaint_resolve"),
    path("hr/salary-plans/", views.hr_salary_plans, name="hr_salary_plans"),
    path("hr/salary-plans/assign/<int:pk>/", views.assign_salary_plan, name="assign_salary_plan"),
    path("hr/salary-requests/", views.hr_salary_requests, name="hr_salary_requests"),
    path(
        "hr/salary-requests/<int:pk>/<str:action>/",
        views.salary_request_decide,
        name="salary_request_decide",
    ),

    # -- tasks --------------------------------------------------------------
    path("tasks/<str:code>/", views.task_detail, name="task_detail"),
    path("tasks/<str:code>/requirement/", views.task_add_requirement, name="task_requirement"),
    path("tasks/<str:code>/words/", views.task_word_count, name="task_word_count"),

    # -- clients ------------------------------------------------------------
    path("clients/", views.client_list, name="client_list"),
    path("clients/<str:code>/", views.client_detail, name="client_detail"),

    # -- stored files: every upload is opened through here (files.py) --------
    path("files/<path:name>", views.serve_file, name="serve_file"),

    # -- notifications ------------------------------------------------------
    path("notifications/", views.notifications, name="notifications"),
    path("sales/line/", views.sales_line, name="sales_line"),

    # -- admin panel --------------------------------------------------------
    path("panel/", views.admin_overview, name="admin_overview"),
    path("panel/settings/", views.admin_settings, name="admin_settings"),
    path("panel/settings/google/connect/", views.google_connect, name="google_connect"),
    path("panel/settings/google/callback/", views.google_callback, name="google_callback"),
    path("panel/settings/google/sync/", views.google_sync, name="google_sync"),
    path("panel/settings/google/disconnect/", views.google_disconnect, name="google_disconnect"),
    path("panel/users/", views.admin_users, name="admin_users"),
    path("panel/users/new/", views.admin_user_new, name="admin_user_new"),
    path("panel/users/<int:pk>/", views.admin_user_edit, name="admin_user_edit"),
    path("panel/users/<int:pk>/shifts/add/", views.admin_shift_add, name="admin_shift_add"),
    path(
        "panel/users/<int:pk>/shifts/<int:shift_id>/delete/",
        views.admin_shift_delete,
        name="admin_shift_delete",
    ),
    path("panel/clients/", views.admin_clients, name="admin_clients"),
    path("panel/clients/new/", views.client_form, name="admin_client_new"),
    path("panel/clients/delete/", views.admin_clients_delete, name="admin_clients_delete"),
    path("panel/clients/<str:code>/edit/", views.client_form, name="admin_client_edit"),
    path("panel/simulate/", views.admin_simulate, name="admin_simulate"),
    path("panel/audit/", views.admin_audit, name="admin_audit"),
    path("panel/reset-tasks/", views.admin_reset_tasks, name="admin_reset_tasks"),
    path("panel/reset-mail/", views.admin_reset_mail, name="admin_reset_mail"),

    # -- json api -----------------------------------------------------------
    path("api/heartbeat/", api.heartbeat, name="api_heartbeat"),
    path("api/attendance/state/", api.attendance_state, name="api_attendance_state"),
    path("api/attendance/punch/", api.attendance_punch, name="api_attendance_punch"),
    path("api/notifications/read/", api.mark_notifications_read, name="api_notifications_read"),
    path("api/prefs/", api.set_prefs, name="api_prefs"),

    # -- /api/v1/: the JSON layer the React front end uses (dashboard/api_v1.py) --
    path("api/v1/me/", api_v1.me, name="v1_me"),
    path("api/v1/notifications/", api_v1.notifications, name="v1_notifications"),
    path("api/v1/notifications/read/", api_v1.notifications_read, name="v1_notifications_read"),
    path("api/v1/chats/", api_v1.chats, name="v1_chats"),
    path("api/v1/rooms/<int:room_id>/messages/", api_v1.room_messages, name="v1_room_messages"),
    path("api/v1/groups/<int:room_id>/messages/", api_v1.group_messages, name="v1_group_messages"),
    path("api/v1/staff/<int:user_id>/messages/", api_v1.staff_messages, name="v1_staff_messages"),
    path("api/v1/clients/<str:client_code>/messages/", api_v1.client_messages, name="v1_client_messages"),
    path("api/v1/groups/<int:room_id>/read/", api_v1.group_read, name="v1_group_read"),
    path("api/v1/clients/<str:client_code>/read/", api_v1.client_read, name="v1_client_read"),
    path("api/v1/groups/<int:room_id>/file-tasks/", api_v1.group_file_tasks, name="v1_group_file_tasks"),
    path("api/v1/staff/<int:user_id>/file-tasks/", api_v1.staff_file_tasks, name="v1_staff_file_tasks"),
    path("api/v1/groups/<int:room_id>/send/", api_v1.group_send, name="v1_group_send"),
    path("api/v1/staff/<int:user_id>/send/", api_v1.staff_send, name="v1_staff_send"),
    path("api/v1/clients/<str:client_code>/send/", api_v1.client_send, name="v1_client_send"),
    path("api/v1/chats/react/", api_v1.chat_react, name="v1_chat_react"),
    path("api/v1/chats/forward/", api_v1.chat_forward, name="v1_chat_forward"),
    path("api/v1/people/", api_v1.people, name="v1_people"),
    path("api/v1/groups/", api_v1.group_create, name="v1_group_create"),
    path("api/v1/groups/<int:room_id>/members/", api_v1.group_members, name="v1_group_members"),
    path("api/v1/groups/<int:room_id>/members/add/", api_v1.group_add, name="v1_group_add"),
    path("api/v1/groups/<int:room_id>/handin-tasks/", api_v1.group_handin_tasks, name="v1_group_handin_tasks"),
    path("api/v1/tasks/<str:code>/hand-in/", api_v1.task_hand_in, name="v1_task_hand_in"),
    path("api/v1/messages/<int:message_id>/confirm/", api_v1.message_confirm, name="v1_message_confirm"),
    path("api/v1/translator/home/", api_v1.translator_home, name="v1_translator_home"),
    path("api/v1/translator/payroll/", api_v1.translator_payroll, name="v1_translator_payroll"),
    path("api/v1/translator/tasks/<str:code>/", api_v1.translator_task, name="v1_translator_task"),
    path("api/v1/assignments/<int:pk>/", api_v1.assignment, name="v1_assignment"),
    path("api/v1/tasks/", api_ops.tasks, name="v1_tasks"),
    path("api/v1/task-form/", api_ops.task_start, name="v1_task_start"),
    path("api/v1/task-form/create/", api_ops.task_create, name="v1_task_create"),
    path("api/v1/team/", api_ops.team, name="v1_team"),
    path("api/v1/attendance/", api_attendance.card, name="v1_attendance"),
    path("api/v1/lead/", api_lead.home, name="v1_lead"),
    path("api/v1/lead/translators/", api_lead.translators, name="v1_lead_translators"),
    path("api/v1/admin/overview/", api_admin.overview, name="v1_admin_overview"),
    path("api/v1/admin/audit/", api_admin.audit, name="v1_admin_audit"),
    path("api/v1/admin/users/", api_admin_users.users, name="v1_admin_users"),
    path("api/v1/admin/users/new/", api_admin_users.user_new, name="v1_admin_user_new"),
    path("api/v1/admin/users/create/", api_admin_users.user_create, name="v1_admin_user_create"),
    path("api/v1/admin/users/<int:pk>/", api_admin_users.user, name="v1_admin_user"),
    path("api/v1/admin/users/<int:pk>/save/", api_admin_users.user_save, name="v1_admin_user_save"),
    path("api/v1/admin/users/<int:pk>/shift/", api_admin_users.user_shift, name="v1_admin_user_shift"),
    path("api/v1/admin/users/<int:pk>/shifts/add/", api_admin_users.shift_add, name="v1_admin_shift_add"),
    path(
        "api/v1/admin/users/<int:pk>/shifts/<int:shift_id>/delete/", api_admin_users.shift_delete,
        name="v1_admin_shift_delete",
    ),
    path("api/v1/admin/aliases/sync/", api_admin_users.aliases_sync, name="v1_admin_aliases_sync"),
    path("api/v1/admin/settings/", api_admin_settings.settings, name="v1_admin_settings"),
    path("api/v1/admin/settings/save/", api_admin_settings.settings_save, name="v1_admin_settings_save"),
    path("api/v1/admin/settings/google/sync/", api_admin_settings.google_sync, name="v1_admin_google_sync"),
    path("api/v1/admin/settings/google/disconnect/", api_admin_settings.google_disconnect, name="v1_admin_google_disconnect"),
    path("api/v1/admin/settings/test/whatsapp/", api_admin_settings.test_whatsapp, name="v1_admin_test_whatsapp"),
    path("api/v1/admin/settings/test/email/", api_admin_settings.test_email, name="v1_admin_test_email"),
    path("api/v1/admin/simulate/", api_admin_tools.simulate, name="v1_admin_simulate"),
    path("api/v1/admin/simulate/send/", api_admin_tools.simulate_send, name="v1_admin_simulate_send"),
    path("api/v1/admin/reset/tasks/", api_admin_tools.reset_tasks_counts, name="v1_admin_reset_tasks"),
    path("api/v1/admin/reset/tasks/run/", api_admin_tools.reset_tasks_run, name="v1_admin_reset_tasks_run"),
    path("api/v1/admin/reset/mail/", api_admin_tools.reset_mail_counts, name="v1_admin_reset_mail"),
    path("api/v1/admin/reset/mail/run/", api_admin_tools.reset_mail_run, name="v1_admin_reset_mail_run"),
    path("api/v1/admin/clients/", api_admin_clients.clients, name="v1_admin_clients"),
    path("api/v1/admin/clients/new/", api_admin_clients.client_new, name="v1_admin_client_new"),
    path("api/v1/admin/clients/create/", api_admin_clients.client_create, name="v1_admin_client_create"),
    path("api/v1/admin/clients/delete-plan/", api_admin_clients.delete_plan, name="v1_admin_clients_plan"),
    path("api/v1/admin/clients/delete/", api_admin_clients.delete, name="v1_admin_clients_delete"),
    path("api/v1/admin/clients/<str:code>/", api_admin_clients.client, name="v1_admin_client"),
    path("api/v1/admin/clients/<str:code>/save/", api_admin_clients.client_save, name="v1_admin_client_save"),
    path("api/v1/tasks/<str:code>/ai-notes/", api_ai.task_notes, name="v1_ai_task_notes"),
    path("api/v1/groups/<int:room_id>/ai-notes/", api_ai.group_notes, name="v1_ai_group_notes"),
    path("api/v1/staff/<int:user_id>/ai-notes/", api_ai.staff_notes, name="v1_ai_staff_notes"),
    path("api/v1/sales/line/", api_sales.line, name="v1_sales_line"),
    path("api/v1/sales/line/save/", api_sales.line_save, name="v1_sales_line_save"),
    path("api/v1/clients/", api_clients.clients, name="v1_clients"),
    path("api/v1/clients/<str:code>/", api_clients.client, name="v1_client"),
    path("api/v1/clients/<str:code>/requirements/", api_clients.client_requirement, name="v1_client_requirement"),
    path("api/v1/mail/threads/", api_mail.threads, name="v1_mail_threads"),
    path("api/v1/mail/threads/<int:pk>/", api_mail.thread, name="v1_mail_thread"),
    path("api/v1/mail/threads/<int:pk>/seen/", api_mail.thread_seen, name="v1_mail_thread_seen"),
    path("api/v1/tasks/<str:code>/", api_ops.task, name="v1_task"),
    path("api/v1/tasks/<str:code>/words/", api_ops.task_words, name="v1_task_words"),
    path("api/v1/tasks/<str:code>/requirements/", api_ops.task_requirement, name="v1_task_requirement"),

    # -- /app/: the page that carries the React app (dashboard/spa.py) --------------
    path("app/", spa.shell, name="app"),
    re_path(r"^app/(?P<path>.+)$", spa.shell, name="app_path"),
    path("assignments/<int:pk>/", views.assignment_preview, name="assignment_preview"),
    path("api/assignments/<int:pk>/accept/", api.accept_assignment, name="api_accept"),
    path("api/assignments/<int:pk>/decline/", api.decline_assignment, name="api_decline"),
    path(
        "api/assignments/<int:pk>/files/",
        api.open_assignment_files, name="api_assignment_files",
    ),
    path("api/tasks/<str:code>/assign-lead/", api.assign_lead, name="api_assign_lead"),
    path(
        "api/tasks/<str:code>/assign-translator/",
        api.assign_translator,
        name="api_assign_translator",
    ),
    path("api/tasks/<str:code>/deadline/", api.set_deadline, name="api_set_deadline"),
    path(
        "api/tasks/<str:code>/translator-deadline/",
        api.set_translator_deadline,
        name="api_set_translator_deadline",
    ),
    path("api/tasks/<str:code>/ai-check/", api.ai_check, name="api_ai_check"),
    path("api/tasks/<str:code>/ai-recheck/", api.ai_recheck, name="api_ai_recheck"),
    path("api/tasks/<str:code>/deliver/", api.deliver, name="api_deliver"),
    path("api/tasks/<str:code>/translation/", api.upload_translation, name="api_task_translation"),
    path("api/tasks/<str:code>/extension/", api.request_extension, name="api_request_extension"),
    path("api/tasks/<str:code>/hand-in/", api.hand_in_from_chat, name="api_task_handin"),
    path(
        "api/extensions/<int:pk>/<str:decision>/",
        api.decide_extension,
        name="api_decide_extension",
    ),
    path("api/integrations/whatsapp/test/", api.whatsapp_test, name="api_whatsapp_test"),
    path("api/integrations/email/test/", api.email_test, name="api_email_test"),
    path("api/tasks/<str:code>/<str:action>/", api.task_action, name="api_task_action"),
    path("api/inbox/feed/", api.inbox_feed, name="api_inbox_feed"),
    path("api/inbox/thread/<int:pk>/feed/", api.mail_thread_feed, name="api_mail_thread_feed"),
    path("api/inbox/thread/<int:pk>/reply/", api.mail_reply, name="api_mail_reply"),
    path("api/messages/<int:pk>/claim/", api.claim_message, name="api_claim_message"),
    path("api/messages/<int:pk>/confirm/", api.confirm_message, name="api_confirm_message"),
    path("api/mail/fetch/", api.fetch_mail, name="api_fetch_mail"),
    path("api/rooms/<int:room_id>/messages/", api.chat_fetch, name="api_chat_fetch"),
    path("api/rooms/<int:room_id>/send/", api.chat_send, name="api_chat_send"),
    path("api/clients/<str:client_code>/requirement/", api.add_requirement, name="api_requirement"),
    path("api/presence/", api.presence, name="api_presence"),
    path("api/client-chats/", api.client_chat_list, name="api_client_chat_list"),
    path("api/chats/forward/", api.chat_forward, name="api_chat_forward"),
    path("api/chats/react/", api.chat_react, name="api_chat_react"),
    path("api/calls/start/", api.call_start, name="api_call_start"),
    path("api/calls/<int:pk>/answer/", api.call_answer, name="api_call_answer"),
    path("api/calls/<int:pk>/end/", api.call_end, name="api_call_end"),
    path("api/calls/<int:pk>/signals/", api.call_signals, name="api_call_signals"),
    path("api/search/tasks/", api.search_tasks, name="api_search_tasks"),
    # Before the "<int:room_id>" routes: "team" is not a room id.
    path("api/groups/team/new/", api.team_group_create, name="api_team_group_create"),
    path("api/groups/<int:room_id>/", api.group_chat_fetch, name="api_group_chat_fetch"),
    path("api/groups/<int:room_id>/members/", api.group_add_members, name="api_group_add_members"),
    path("api/groups/<int:room_id>/send/", api.group_chat_send, name="api_group_chat_send"),
    path("api/client-chats/<str:client_code>/", api.client_chat_fetch, name="api_client_chat_fetch"),
    path(
        "api/client-chats/<str:client_code>/send/",
        api.client_chat_send,
        name="api_client_chat_send",
    ),

    # -- webhooks -----------------------------------------------------------
    path("webhooks/whatsapp/", webhooks.whatsapp_hook, name="wh_whatsapp"),
    path("webhooks/email/", webhooks.email_hook, name="wh_email"),

    # Last on purpose: anything else under /api/v1/ is a JSON 404. A v1 route
    # added after this line would be shadowed by it.
    re_path(r"^api/v1/", api_v1.not_found, name="v1_not_found"),
]
