"""URL map for the Eagle dashboard app."""

from django.urls import path, re_path

from . import (
    api, api_accounts, api_admin, api_admin_clients, api_admin_settings, api_admin_tools, api_admin_users, api_ai, api_attendance, api_candidates, api_clients, api_help, api_hiring, api_hr, api_lead, api_leave, api_people, api_profile, api_recruit, api_mail, api_ops, api_sales, api_support, api_v1, legacy, spa, views,
    webhooks,
)

app_name = "dashboard"

urlpatterns = [
    # -- auth ---------------------------------------------------------------
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.home, name="home"),
    path("healthz", views.healthz, name="healthz"),

    # -- public legal pages (no login) --------------------------------------
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
    path("data-deletion/", views.data_deletion, name="data_deletion"),

    # -- stored files: every upload is opened through here (files.py) --------
    path("files/<path:name>", views.serve_file, name="serve_file"),

    # -- Google sign-in for the mailbox: a redirect round trip, not a page (the settings' own doors sync and disconnect) --
    path("panel/settings/google/connect/", views.google_connect, name="google_connect"),
    path("panel/settings/google/callback/", views.google_callback, name="google_callback"),

    # -- the classic interface's addresses, as redirects into the app (legacy.py) --
    *legacy.urlpatterns,

    # -- json api -----------------------------------------------------------
    path("api/heartbeat/", api.heartbeat, name="api_heartbeat"),
    path("api/attendance/punch/", api.attendance_punch, name="api_attendance_punch"),
    path("api/prefs/", api.set_prefs, name="api_prefs"),

    # -- /api/v1/: the JSON layer the React front end uses (dashboard/api_v1.py) --
    path("api/v1/me/", api_v1.me, name="v1_me"),
    path("api/v1/me/avatar/", api_profile.avatar_set, name="v1_me_avatar"),
    path("api/v1/me/avatar/remove/", api_profile.avatar_remove, name="v1_me_avatar_remove"),
    path("api/v1/me/password/", api_profile.password_change, name="v1_me_password"),
    path("api/v1/help/", api_help.home, name="v1_help"),
    path("api/v1/help/ask/", api_help.ask, name="v1_help_ask"),
    path("api/v1/help/orders/<int:pk>/run/", api_help.order_run, name="v1_help_order_run"),
    path("api/v1/help/orders/<int:pk>/cancel/", api_help.order_cancel, name="v1_help_order_cancel"),
    path("api/v1/notifications/", api_v1.notifications, name="v1_notifications"),
    path("api/v1/notifications/read/", api_v1.notifications_read, name="v1_notifications_read"),
    path("api/v1/chats/", api_v1.chats, name="v1_chats"),
    path("api/v1/rooms/<int:room_id>/messages/", api_v1.room_messages, name="v1_room_messages"),
    path("api/v1/groups/<int:room_id>/messages/", api_v1.group_messages, name="v1_group_messages"),
    path("api/v1/staff/<int:user_id>/messages/", api_v1.staff_messages, name="v1_staff_messages"),
    path("api/v1/clients/<str:client_code>/messages/", api_v1.client_messages, name="v1_client_messages"),
    path("api/v1/groups/<int:room_id>/read/", api_v1.group_read, name="v1_group_read"),
    path("api/v1/clients/<str:client_code>/read/", api_v1.client_read, name="v1_client_read"),
    path("api/v1/groups/<int:room_id>/file-tasks/", api_v1.group_file_tasks, name="v1_group_file_tasks"),
    path("api/v1/staff/<int:user_id>/file-tasks/", api_v1.staff_file_tasks, name="v1_staff_file_tasks"),
    path("api/v1/groups/<int:room_id>/send/", api_v1.group_send, name="v1_group_send"),
    path("api/v1/staff/<int:user_id>/send/", api_v1.staff_send, name="v1_staff_send"),
    path("api/v1/clients/<str:client_code>/send/", api_v1.client_send, name="v1_client_send"),
    path("api/v1/chats/react/", api_v1.chat_react, name="v1_chat_react"),
    path("api/v1/chats/forward/", api_v1.chat_forward, name="v1_chat_forward"),
    path("api/v1/chats/unsend/", api_v1.chat_unsend, name="v1_chat_unsend"),
    path("api/v1/chats/mute/", api_v1.chat_mute, name="v1_chat_mute"),
    path("api/v1/people/", api_v1.people, name="v1_people"),
    path("api/v1/groups/", api_v1.group_create, name="v1_group_create"),
    path("api/v1/groups/<int:room_id>/members/", api_v1.group_members, name="v1_group_members"),
    path("api/v1/groups/<int:room_id>/members/add/", api_v1.group_add, name="v1_group_add"),
    path("api/v1/groups/<int:room_id>/handin-tasks/", api_v1.group_handin_tasks, name="v1_group_handin_tasks"),
    path("api/v1/tasks/<str:code>/hand-in/", api_v1.task_hand_in, name="v1_task_hand_in"),
    path("api/v1/messages/<int:message_id>/confirm/", api_v1.message_confirm, name="v1_message_confirm"),
    path("api/v1/translator/home/", api_v1.translator_home, name="v1_translator_home"),
    path("api/v1/translator/payroll/", api_v1.translator_payroll, name="v1_translator_payroll"),
    path("api/v1/translator/tasks/<str:code>/", api_v1.translator_task, name="v1_translator_task"),
    path("api/v1/assignments/<int:pk>/", api_v1.assignment, name="v1_assignment"),
    path("api/v1/tasks/", api_ops.tasks, name="v1_tasks"),
    path("api/v1/task-form/", api_ops.task_start, name="v1_task_start"),
    path("api/v1/task-form/create/", api_ops.task_create, name="v1_task_create"),
    path("api/v1/team/", api_ops.team, name="v1_team"),
    path("api/v1/announce/", api_support.announce, name="v1_announce"),
    path("api/v1/attendance/", api_attendance.card, name="v1_attendance"),
    path("api/v1/lead/", api_lead.home, name="v1_lead"),
    path("api/v1/lead/translators/", api_lead.translators, name="v1_lead_translators"),
    path("api/v1/accounts/overview/", api_accounts.overview, name="v1_accounts_overview"),
    path("api/v1/accounts/recalculate/", api_accounts.recalculate, name="v1_accounts_recalculate"),
    path("api/v1/accounts/periods/<int:pk>/approve/", api_accounts.period_approve, name="v1_accounts_period_approve"),
    path("api/v1/accounts/lines/<int:pk>/", api_accounts.line, name="v1_accounts_line"),
    path("api/v1/accounts/lines/<int:pk>/bonus/", api_accounts.line_bonus, name="v1_accounts_line_bonus"),
    path("api/v1/accounts/attendance/", api_accounts.attendance_sheet, name="v1_accounts_attendance"),
    path("api/v1/accounts/attendance/refresh/", api_accounts.attendance_refresh, name="v1_accounts_attendance_refresh"),
    path("api/v1/accounts/attendance/save/", api_accounts.attendance_save, name="v1_accounts_attendance_save"),
    path("api/v1/accounts/violations/", api_accounts.violations, name="v1_accounts_violations"),
    path("api/v1/accounts/violations/create/", api_accounts.violation_create, name="v1_accounts_violation_create"),
    path(
        "api/v1/accounts/violations/<int:pk>/<str:action>/", api_accounts.violation_decide,
        name="v1_accounts_violation_decide",
    ),
    path("api/v1/accounts/salary/<int:pk>/", api_accounts.salary, name="v1_accounts_salary"),
    path("api/v1/accounts/salary/<int:pk>/save/", api_accounts.salary_save, name="v1_accounts_salary_save"),
    path("api/v1/accounts/rules/", api_accounts.rules, name="v1_accounts_rules"),
    path("api/v1/accounts/rules/save/", api_accounts.rules_save, name="v1_accounts_rules_save"),
    path("api/v1/accounts/rules/tiers/add/", api_accounts.tier_add, name="v1_accounts_tier_add"),
    path("api/v1/accounts/rules/tiers/<int:pk>/delete/", api_accounts.tier_delete, name="v1_accounts_tier_delete"),
    # -- HR: the attendance side ---------------------------------------------
    path("api/v1/hr/attendance/", api_hr.board, name="v1_hr_board"),
    path("api/v1/hr/attendance/<int:pk>/", api_hr.day, name="v1_hr_day"),
    path("api/v1/hr/attendance/<int:pk>/save/", api_hr.day_save, name="v1_hr_day_save"),
    path("api/v1/hr/attendance/<int:pk>/clear/", api_hr.day_clear, name="v1_hr_day_clear"),
    path("api/v1/hr/report/", api_hr.report, name="v1_hr_report"),
    path("api/v1/hr/schedules/", api_hr.schedules, name="v1_hr_schedules"),
    path("api/v1/hr/schedules/shift/", api_hr.shift_add, name="v1_hr_shift_add"),
    path("api/v1/hr/schedules/shift/<int:pk>/delete/", api_hr.shift_delete, name="v1_hr_shift_delete"),
    path("api/v1/hr/schedules/override/", api_hr.override_add, name="v1_hr_override_add"),
    path("api/v1/hr/schedules/override/<int:pk>/delete/", api_hr.override_delete, name="v1_hr_override_delete"),
    path("api/v1/hr/schedules/template/", api_hr.template_add, name="v1_hr_template_add"),
    path("api/v1/hr/shifts/", api_hr.shifts, name="v1_hr_shifts"),
    path("api/v1/hr/shifts/save/", api_hr.shift_save, name="v1_hr_shift_save"),
    path("api/v1/hr/shifts/<int:pk>/delete/", api_hr.shift_template_delete, name="v1_hr_shift_template_delete"),
    path("api/v1/hr/offices/", api_hr.offices, name="v1_hr_offices"),
    path("api/v1/hr/offices/save/", api_hr.office_save, name="v1_hr_office_save"),
    path("api/v1/hr/offices/<int:pk>/delete/", api_hr.office_delete, name="v1_hr_office_delete"),
    path("api/v1/hr/devices/", api_hr.devices, name="v1_hr_devices"),
    path("api/v1/hr/devices/<int:pk>/<str:action>/", api_hr.device_decide, name="v1_hr_device_decide"),
    path("api/v1/hr/overtime/", api_hr.overtime, name="v1_hr_overtime"),
    path("api/v1/hr/overtime/<int:pk>/<str:action>/", api_hr.overtime_decide, name="v1_hr_overtime_decide"),
    path("api/v1/hr/leave/", api_hr.leave_queue, name="v1_hr_leave"),
    # -- HR: the people already hired ----------------------------------------------
    path("api/v1/hr/employees/", api_people.register, name="v1_hr_register"),
    path("api/v1/hr/employees/<int:pk>/", api_people.employee, name="v1_hr_employee"),
    path("api/v1/hr/employees/<int:pk>/shift/", api_people.employee_shift, name="v1_hr_employee_shift"),
    path("api/v1/hr/employees/<int:pk>/work-mode/", api_people.employee_workmode, name="v1_hr_employee_workmode"),
    path("api/v1/hr/employees/<int:pk>/plan/", api_people.employee_plan, name="v1_hr_employee_plan"),
    path("api/v1/hr/penalties/", api_people.penalty_list, name="v1_hr_penalties"),
    path("api/v1/hr/penalties/<int:pk>/<str:action>/", api_people.penalty_decide, name="v1_hr_penalty_decide"),
    path("api/v1/hr/probation/", api_people.probation, name="v1_hr_probation"),
    path("api/v1/hr/probation/<int:pk>/decide/", api_people.probation_decide, name="v1_hr_probation_decide"),
    path("api/v1/hr/probation/open/<int:pk>/", api_people.probation_open, name="v1_hr_probation_open"),
    path("api/v1/hr/performance/", api_people.performance_report, name="v1_hr_performance"),
    path("api/v1/hr/performance/board/", api_people.performance_board, name="v1_hr_performance_board"),
    path("api/v1/hr/complaints/", api_people.complaints, name="v1_hr_complaints"),
    path("api/v1/hr/complaints/create/", api_people.complaint_create, name="v1_hr_complaint_create"),
    path("api/v1/hr/complaints/<int:pk>/resolve/", api_people.complaint_resolve, name="v1_hr_complaint_resolve"),
    path("api/v1/hr/salary-requests/", api_people.salary_requests, name="v1_hr_salary_requests"),
    path("api/v1/hr/salary-requests/create/", api_people.salary_request_create, name="v1_hr_salary_request_create"),
    path("api/v1/hr/salary-requests/<int:pk>/<str:action>/", api_people.salary_request_decide, name="v1_hr_salary_request_decide"),
    path("api/v1/hr/salary-plans/", api_people.salary_plans, name="v1_hr_salary_plans"),
    path("api/v1/hr/salary-plans/save/", api_people.salary_plan_save, name="v1_hr_salary_plan_save"),
    # -- HR: recruitment, the pipeline side ---------------------------------------
    path("api/v1/hr/recruitment/", api_recruit.board, name="v1_hr_recruitment"),
    path("api/v1/hr/recruitment/settings/", api_recruit.recruitment_settings, name="v1_hr_recruitment_settings"),
    path("api/v1/hr/recruitment/settings/save/", api_recruit.recruitment_settings_save, name="v1_hr_recruitment_settings_save"),
    path("api/v1/hr/vacancies/", api_recruit.vacancies, name="v1_hr_vacancies"),
    path("api/v1/hr/vacancies/create/", api_recruit.vacancy_create, name="v1_hr_vacancy_create"),
    path("api/v1/hr/vacancies/questions/<int:pk>/delete/", api_recruit.vacancy_question_delete, name="v1_hr_vacancy_question_delete"),
    path("api/v1/hr/vacancies/<str:code>/", api_recruit.vacancy, name="v1_hr_vacancy"),
    path("api/v1/hr/vacancies/<str:code>/save/", api_recruit.vacancy_save, name="v1_hr_vacancy_save"),
    path("api/v1/hr/vacancies/<str:code>/questions/", api_recruit.vacancy_question_add, name="v1_hr_vacancy_question_add"),
    path("api/v1/hr/vacancies/<str:code>/questions/order/", api_recruit.vacancy_questions_order, name="v1_hr_vacancy_questions_order"),
    path("api/v1/hr/questions/", api_recruit.questions, name="v1_hr_questions"),
    path("api/v1/hr/questions/save/", api_recruit.question_save, name="v1_hr_question_save"),
    path("api/v1/hr/departments/", api_recruit.department_add, name="v1_hr_department_add"),
    # -- HR: recruitment, the candidates' side -------------------------------------
    path("api/v1/hr/candidates/", api_candidates.candidates, name="v1_hr_candidates"),
    path("api/v1/hr/candidates/<str:code>/", api_candidates.candidate, name="v1_hr_candidate"),
    path("api/v1/hr/candidates/<str:code>/save/", api_candidates.candidate_save, name="v1_hr_candidate_save"),
    path("api/v1/hr/candidates/<str:code>/cv/", api_candidates.candidate_cv, name="v1_hr_candidate_cv"),
    path("api/v1/hr/candidates/<str:code>/status/", api_candidates.candidate_status, name="v1_hr_candidate_status"),
    path("api/v1/hr/candidates/<str:code>/reveal/", api_candidates.candidate_reveal, name="v1_hr_candidate_reveal"),
    path("api/v1/hr/candidates/<str:code>/message/", api_candidates.candidate_message, name="v1_hr_candidate_message"),
    path("api/v1/hr/candidates/<str:code>/interviews/", api_candidates.interview_create, name="v1_hr_interview_create"),
    path("api/v1/hr/candidates/<str:code>/tests/", api_candidates.candidate_test_create, name="v1_hr_candidate_test_create"),
    path("api/v1/hr/candidates/<str:code>/hire/", api_hiring.hire_form, name="v1_hr_hire_form"),
    path("api/v1/hr/candidates/<str:code>/hire/save/", api_hiring.hire, name="v1_hr_hire"),
    path("api/v1/hr/interviews/<int:pk>/", api_candidates.interview, name="v1_hr_interview"),
    path("api/v1/hr/interviews/<int:pk>/score/", api_candidates.interview_score, name="v1_hr_interview_score"),
    path("api/v1/hr/approvals/", api_hiring.approvals, name="v1_hr_approvals"),
    path("api/v1/hr/approvals/<str:code>/<str:action>/", api_hiring.approval_decide, name="v1_hr_approval_decide"),
    path("api/v1/reviewer/tests/", api_hiring.reviewer_tests, name="v1_reviewer_tests"),
    path("api/v1/reviewer/tests/<int:pk>/", api_hiring.reviewer_test, name="v1_reviewer_test"),
    path("api/v1/reviewer/tests/<int:pk>/score/", api_hiring.reviewer_test_score, name="v1_reviewer_test_score"),
    # -- leave: a person's own, and the decision ------------------------------
    path("api/v1/leave/", api_leave.mine, name="v1_leave"),
    path("api/v1/leave/request/", api_leave.ask, name="v1_leave_request"),
    path("api/v1/leave/<int:pk>/cancel/", api_leave.cancel, name="v1_leave_cancel"),
    path("api/v1/leave/<int:pk>/<str:action>/", api_leave.decide, name="v1_leave_decide"),
    path("api/v1/admin/overview/", api_admin.overview, name="v1_admin_overview"),
    path("api/v1/admin/audit/", api_admin.audit, name="v1_admin_audit"),
    path("api/v1/admin/users/new/", api_admin_users.user_new, name="v1_admin_user_new"),
    path("api/v1/admin/users/create/", api_admin_users.user_create, name="v1_admin_user_create"),
    path("api/v1/admin/users/<int:pk>/", api_admin_users.user, name="v1_admin_user"),
    path("api/v1/admin/users/<int:pk>/save/", api_admin_users.user_save, name="v1_admin_user_save"),
    path("api/v1/admin/users/<int:pk>/shifts/add/", api_admin_users.shift_add, name="v1_admin_shift_add"),
    path(
        "api/v1/admin/users/<int:pk>/shifts/<int:shift_id>/delete/", api_admin_users.shift_delete,
        name="v1_admin_shift_delete",
    ),
    path("api/v1/admin/aliases/sync/", api_admin_users.aliases_sync, name="v1_admin_aliases_sync"),
    path("api/v1/admin/settings/", api_admin_settings.settings, name="v1_admin_settings"),
    path("api/v1/admin/settings/save/", api_admin_settings.settings_save, name="v1_admin_settings_save"),
    path("api/v1/admin/settings/google/sync/", api_admin_settings.google_sync, name="v1_admin_google_sync"),
    path("api/v1/admin/settings/google/disconnect/", api_admin_settings.google_disconnect, name="v1_admin_google_disconnect"),
    path("api/v1/admin/settings/test/whatsapp/", api_admin_settings.test_whatsapp, name="v1_admin_test_whatsapp"),
    path("api/v1/admin/settings/test/email/", api_admin_settings.test_email, name="v1_admin_test_email"),
    path("api/v1/admin/simulate/", api_admin_tools.simulate, name="v1_admin_simulate"),
    path("api/v1/admin/simulate/send/", api_admin_tools.simulate_send, name="v1_admin_simulate_send"),
    path("api/v1/admin/reset/tasks/", api_admin_tools.reset_tasks_counts, name="v1_admin_reset_tasks"),
    path("api/v1/admin/reset/tasks/run/", api_admin_tools.reset_tasks_run, name="v1_admin_reset_tasks_run"),
    path("api/v1/admin/reset/mail/", api_admin_tools.reset_mail_counts, name="v1_admin_reset_mail"),
    path("api/v1/admin/reset/mail/run/", api_admin_tools.reset_mail_run, name="v1_admin_reset_mail_run"),
    path("api/v1/admin/reset/staff/", api_admin_tools.reset_staff_counts, name="v1_admin_reset_staff"),
    path("api/v1/admin/reset/staff/run/", api_admin_tools.reset_staff_run, name="v1_admin_reset_staff_run"),
    path("api/v1/admin/clients/", api_admin_clients.clients, name="v1_admin_clients"),
    path("api/v1/admin/clients/new/", api_admin_clients.client_new, name="v1_admin_client_new"),
    path("api/v1/admin/clients/create/", api_admin_clients.client_create, name="v1_admin_client_create"),
    path("api/v1/admin/clients/delete-plan/", api_admin_clients.delete_plan, name="v1_admin_clients_plan"),
    path("api/v1/admin/clients/delete/", api_admin_clients.delete, name="v1_admin_clients_delete"),
    path("api/v1/admin/clients/<str:code>/", api_admin_clients.client, name="v1_admin_client"),
    path("api/v1/admin/clients/<str:code>/save/", api_admin_clients.client_save, name="v1_admin_client_save"),
    path("api/v1/tasks/<str:code>/ai-notes/", api_ai.task_notes, name="v1_ai_task_notes"),
    path("api/v1/tasks/<str:code>/ai-notes/accept/", api_ai.accept, name="v1_ai_accept"),
    path("api/v1/groups/<int:room_id>/ai-notes/", api_ai.group_notes, name="v1_ai_group_notes"),
    path("api/v1/staff/<int:user_id>/ai-notes/", api_ai.staff_notes, name="v1_ai_staff_notes"),
    path("api/v1/sales/line/", api_sales.line, name="v1_sales_line"),
    path("api/v1/sales/line/save/", api_sales.line_save, name="v1_sales_line_save"),
    path("api/v1/clients/", api_clients.clients, name="v1_clients"),
    path("api/v1/clients/<str:code>/", api_clients.client, name="v1_client"),
    path("api/v1/clients/<str:code>/requirements/", api_clients.client_requirement, name="v1_client_requirement"),
    path("api/v1/mail/threads/", api_mail.threads, name="v1_mail_threads"),
    path("api/v1/mail/threads/<int:pk>/", api_mail.thread, name="v1_mail_thread"),
    path("api/v1/mail/threads/<int:pk>/seen/", api_mail.thread_seen, name="v1_mail_thread_seen"),
    path("api/v1/tasks/<str:code>/", api_ops.task, name="v1_task"),
    path("api/v1/tasks/<str:code>/words/", api_ops.task_words, name="v1_task_words"),
    path("api/v1/tasks/<str:code>/requirements/", api_ops.task_requirement, name="v1_task_requirement"),

    # -- /app/: the page that carries the React app (dashboard/spa.py) --------------
    path("app/", spa.shell, name="app"),
    re_path(r"^app/(?P<path>.+)$", spa.shell, name="app_path"),
    path("api/assignments/<int:pk>/accept/", api.accept_assignment, name="api_accept"),
    path("api/assignments/<int:pk>/decline/", api.decline_assignment, name="api_decline"),
    path(
        "api/assignments/<int:pk>/files/",
        api.open_assignment_files, name="api_assignment_files",
    ),
    path("api/tasks/<str:code>/assign-lead/", api.assign_lead, name="api_assign_lead"),
    path(
        "api/tasks/<str:code>/assign-translator/",
        api.assign_translator,
        name="api_assign_translator",
    ),
    path(
        "api/tasks/<str:code>/assign-translator-direct/",
        api.assign_translator_direct,
        name="api_assign_translator_direct",
    ),
    path("api/tasks/<str:code>/deadline/", api.set_deadline, name="api_set_deadline"),
    path(
        "api/tasks/<str:code>/translator-deadline/",
        api.set_translator_deadline,
        name="api_set_translator_deadline",
    ),
    path("api/tasks/<str:code>/ai-check/", api.ai_check, name="api_ai_check"),
    path("api/tasks/<str:code>/ai-recheck/", api.ai_recheck, name="api_ai_recheck"),
    path("api/tasks/<str:code>/deliver/", api.deliver, name="api_deliver"),
    path("api/tasks/<str:code>/translation/", api.upload_translation, name="api_task_translation"),
    path("api/tasks/<str:code>/extension/", api.request_extension, name="api_request_extension"),
    path(
        "api/extensions/<int:pk>/<str:decision>/",
        api.decide_extension,
        name="api_decide_extension",
    ),
    path("api/tasks/<str:code>/<str:action>/", api.task_action, name="api_task_action"),
    path("api/inbox/thread/<int:pk>/reply/", api.mail_reply, name="api_mail_reply"),
    path("api/mail/fetch/", api.fetch_mail, name="api_fetch_mail"),
    path("api/calls/start/", api.call_start, name="api_call_start"),
    path("api/calls/<int:pk>/answer/", api.call_answer, name="api_call_answer"),
    path("api/calls/<int:pk>/end/", api.call_end, name="api_call_end"),
    path("api/calls/<int:pk>/signals/", api.call_signals, name="api_call_signals"),
    path("api/search/tasks/", api.search_tasks, name="api_search_tasks"),

    # -- webhooks -----------------------------------------------------------
    path("webhooks/whatsapp/", webhooks.whatsapp_hook, name="wh_whatsapp"),
    path("webhooks/email/", webhooks.email_hook, name="wh_email"),

    # Last on purpose: anything else under /api/v1/ is a JSON 404. A v1 route
    # added after this line would be shadowed by it.
    re_path(r"^api/v1/", api_v1.not_found, name="v1_not_found"),
]
