# Generated by Django 5.2.5 on 2026-09-07 21:38

import dashboard.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('ai_check_enabled', models.BooleanField(default=False)),
                ('claude_api_key', models.CharField(blank=True, max_length=250)),
                ('claude_model', models.CharField(default='claude-sonnet-4-5', max_length=80)),
                ('response_window_seconds', models.PositiveIntegerField(default=60)),
                ('deadline_warning_minutes', models.PositiveIntegerField(default=15)),
                ('penalty_value', models.DecimalField(decimal_places=3, default=Decimal('0.125'), max_digits=5)),
                ('max_rating', models.DecimalField(decimal_places=3, default=Decimal('5.000'), max_digits=5)),
                ('rate_keywords', models.TextField(default='rate,rates,rating,ratings,ريت,الريت,سعر,الاسعار', help_text='Comma separated. A message containing any of these is hidden from Operation.')),
                ('whatsapp_verify_token', models.CharField(blank=True, max_length=120)),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=400)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=60)),
                ('webhook_shared_secret', models.CharField(blank=True, max_length=120)),
                ('imap_host', models.CharField(blank=True, max_length=120)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_user', models.CharField(blank=True, max_length=190)),
                ('imap_password', models.CharField(blank=True, max_length=250)),
                ('imap_folder', models.CharField(default='INBOX', max_length=60)),
                ('simulation_enabled', models.BooleanField(default=True)),
                ('poll_ms', models.PositiveIntegerField(default=3000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('admin_notes', models.TextField(blank=True, help_text='Visible to the admin only.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operation', 'Operation'), ('team_lead', 'Team Leader'), ('translator', 'Translator')], default='translator', max_length=20)),
                ('display_name_ar', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('languages', models.CharField(blank=True, help_text='e.g. EN, AR, FR', max_length=160)),
                ('rating', models.DecimalField(decimal_places=3, default=Decimal('5.000'), max_digits=5)),
                ('force_offline', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('ui_lang', models.CharField(default='ar', max_length=5)),
                ('ui_theme', models.CharField(default='dark', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Only used for translators: which team leader they report to.', limit_choices_to={'role': 'team_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('role', 'username'),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target', models.CharField(blank=True, max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('system_key', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dashboard.models.upload_chat)),
                ('original_name', models.CharField(blank=True, max_length=250)),
                ('size', models.BigIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ops_lead', 'Operation + Team leader'), ('group', 'Operation + Team leader + Translator')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.chatroom'),
        ),
        migrations.CreateModel(
            name='ClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('like', 'Likes'), ('dislike', 'Dislikes'), ('rule', 'Rule')], default='rule', max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='dashboard.client')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('manual', 'Manual')], default='whatsapp', max_length=12)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=190)),
                ('sender_identity', models.CharField(blank=True, max_length=190)),
                ('sender_display', models.CharField(blank=True, max_length=190)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_rate_blocked', models.BooleanField(default=False)),
                ('blocked_keyword', models.CharField(blank=True, max_length=60)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_messages', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='dashboard.client')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dashboard.models.upload_inbound)),
                ('original_name', models.CharField(blank=True, max_length=250)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.inboundmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_lang', models.CharField(blank=True, max_length=40)),
                ('target_lang', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('awaiting_lead', 'Awaiting team leader'), ('lead_accepted', 'Team leader accepted'), ('awaiting_translator', 'Awaiting translator'), ('in_progress', 'In progress'), ('under_review', 'Under review'), ('reviewed', 'Reviewed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=24)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('deadline_warned_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_missed_notified', models.BooleanField(default=False)),
                ('lead_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('translator_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='dashboard.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translator_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=3, max_digits=5)),
                ('reason_en', models.CharField(blank=True, max_length=200)),
                ('reason_ar', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_events', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.task')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_messages', to='dashboard.task'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dashboard.task'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('admin', 'Admin'), ('operation', 'Operation'), ('team_lead', 'Team Leader'), ('translator', 'Translator')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.task')),
            ],
            options={
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='AICheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('clean', 'No issues'), ('issues', 'Issues found'), ('error', 'Error')], default='clean', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_checks', to='dashboard.task')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('body_ar', models.CharField(blank=True, max_length=400)),
                ('body_en', models.CharField(blank=True, max_length=400)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('sound', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.task')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='dashboard_n_user_id_a3805d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['is_rate_blocked', '-received_at'], name='dashboard_i_is_rate_807edd_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('task', 'kind'), name='uniq_room_per_task_kind'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'expires_at'], name='dashboard_a_status_69ee59_idx'),
        ),
    ]
