# Generated by Django 5.2.5 on 2026-09-08 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='smtp_from',
            field=models.CharField(blank=True, max_length=190),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='Leave blank to derive it from the IMAP host (imap. -> smtp.).', max_length=120),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Blank = reuse the IMAP password.', max_length=250),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_user',
            field=models.CharField(blank=True, help_text='Blank = reuse the IMAP user.', max_length=190),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_api_version',
            field=models.CharField(default='v21.0', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_app_secret',
            field=models.CharField(blank=True, help_text='Meta App Secret — used to verify the X-Hub-Signature-256 header.', max_length=200),
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('manual', 'Manual')], max_length=12)),
                ('to_identity', models.CharField(blank=True, max_length=190)),
                ('body', models.TextField(blank=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Closed without sending')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('provider_id', models.CharField(blank=True, max_length=190)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='dashboard.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='dashboard.task')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
