# Generated by Django 5.2.5 on 2026-09-09 23:32

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_appsettings_smtp_from_appsettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('delivery', 'Task delivery'), ('chat', 'Chat reply')], default='delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='whatsapp_api_version',
            field=models.CharField(default='v23.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='dashboard.task'),
        ),
        migrations.CreateModel(
            name='OutboundAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dashboard.models.upload_outbound)),
                ('original_name', models.CharField(blank=True, max_length=250)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='dashboard.outboundmessage')),
            ],
        ),
    ]
