# Generated by Django 5.2.17 on 2026-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_attendance_gate_extra_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='new_ui',
            field=models.JSONField(blank=True, default=dict, help_text='Which roles and people see the new version of each ported screen.'),
        ),
    ]
