# Generated by Django 5.2.17 on 2026-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_new_ui_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Closed without sending')], default='sent', max_length=10),
        ),
    ]
