# Generated by Django 5.2.17 on 2026-10-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_outbound_sending_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='new_ui',
        ),
    ]
