# Generated by Django 5.2.17 on 2026-10-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_drop_new_ui_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='imap_read_spam',
            field=models.BooleanField(default=False, help_text="Also read the mailbox's Spam folder."),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mail_uid_state',
            field=models.TextField(blank=True, default=''),
        ),
    ]
