# Generated by Django 5.2.17 on 2026-10-05 08:44

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_mail_spam_and_uid_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.upload_avatar),
        ),
    ]
