# Generated by Django 5.2.17 on 2026-10-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_owner_has_no_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='helpbot_actions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='helpbot_ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HelpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('params', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the owner'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Refused'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HelpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('page', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('guide', 'Guide'), ('none', 'No answer'), ('action', 'Order')], max_length=8)),
                ('guides', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='helpq_user_when')],
            },
        ),
    ]
