# Generated by Django 5.2.17 on 2026-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_helpbot_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpquestion',
            name='ai_call',
            field=models.BooleanField(default=False),
        ),
    ]
