# Generated by Django 5.2.17 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_helpquestion_ai_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='target_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operation', 'Operation'), ('team_lead', 'Team Leader'), ('translator', 'Translator'), ('hr', 'HR'), ('reviewer', 'Reviewer'), ('accounting', 'Accounting'), ('sales', 'Sales'), ('support', 'Technical support')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operation', 'Operation'), ('team_lead', 'Team Leader'), ('translator', 'Translator'), ('hr', 'HR'), ('reviewer', 'Reviewer'), ('accounting', 'Accounting'), ('sales', 'Sales'), ('support', 'Technical support')], default='translator', max_length=20),
        ),
    ]
