# Generated by Django 5.2.17 on 2026-10-06 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_support_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
