# Generated by Django 5.2.17 on 2026-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body_ar',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body_en',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
