# Generated by Django 5.2.17 on 2026-10-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_penalty_decision_and_ai_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicheckresult',
            name='accepted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('awaiting_lead', 'Awaiting team leader'), ('lead_accepted', 'Team leader accepted'), ('awaiting_translator', 'Awaiting translator'), ('in_progress', 'In progress'), ('under_review', 'Under review'), ('reviewed', 'Awaiting delivery to the client'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=24),
        ),
        migrations.DeleteModel(
            name='AIRevision',
        ),
    ]
