# Generated by Django 5.2.17 on 2026-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_ai_accept_costs_stars_drop_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='translator_level',
            field=models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('junior', 'Junior Translator'), ('translator', 'Translator'), ('senior', 'Senior Translator'), ('expert', 'Expert Translator')], default='', max_length=10),
        ),
    ]
