# Generated by Django 5.2.17 on 2026-10-07 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_user_translator_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='unsent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='dashboard.client')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='dashboard.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('user', 'room'), name='uniq_mute_room'), models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('user', 'client'), name='uniq_mute_client'), models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('room__isnull', False)), models.Q(('client__isnull', False), ('room__isnull', True)), _connector='OR'), name='mute_has_one_target')],
            },
        ),
    ]
