# Generated by Django 5.2.17 on 2026-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_chat_mute_and_unsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='words_open',
            field=models.BooleanField(default=False),
        ),
    ]
