# Generated by Django 5.2.17 on 2026-10-07 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_chat_words_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
