# Generated by Django 5.2.17 on 2026-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_manual_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reviewed_version',
            field=models.BooleanField(default=False),
        ),
    ]
