# Generated by Django 5.2.17 on 2026-10-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_chat_reviewed_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='page_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='page_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='source_lang',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_lang',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='assignment',
            name='words',
            field=models.PositiveIntegerField(default=0, help_text='Words the leader gave this translator. 0 = not said.'),
        ),
    ]
