# Generated by Django 5.2.17 on 2026-10-08 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def name_the_translator(apps, schema_editor):
    """Every check made before this judged the task's one translator: say so, so that "no translator" can only mean nobody.

    Before this release a task never had more than one translator, so the task's translator is the right name. A check on a task nobody
    holds stays empty.
    """
    Check = apps.get_model("dashboard", "AICheckResult")
    Task = apps.get_model("dashboard", "Task")
    Check.objects.filter(translator__isnull=True).update(
        translator_id=models.Subquery(Task.objects.filter(pk=models.OuterRef("task_id")).values("translator_id")[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_assignment_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicheckresult',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(name_the_translator, migrations.RunPython.noop),
    ]
