# Generated by Django 5.2.17 on 2026-10-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_aicheck_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingevent',
            name='ai_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.aicheckresult'),
        ),
        migrations.AddField(
            model_name='ratingevent',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
