# Generated by Django 5.2.17 on 2026-10-10 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_ratingevent_ai_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales_manager',
            field=models.BooleanField(default=False, help_text='Sales only: makes the B2B company sheets, gives each to a Sales person and reads all of them.'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('website', models.CharField(blank=True, max_length=250)),
                ('industry', models.CharField(blank=True, help_text='Industry / company type.', max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('linkedin', models.CharField(blank=True, max_length=250)),
                ('languages', models.CharField(blank=True, help_text='Languages / language pairs.', max_length=250)),
                ('services', models.CharField(blank=True, help_text='Services required.', max_length=250)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New lead'), ('email_sent', 'Email sent'), ('follow_up_1', 'Follow-up 1'), ('follow_up_2', 'Follow-up 2'), ('meeting', 'Meeting scheduled'), ('proposal', 'Proposal / rate sheet sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=12)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('phone_key', models.CharField(blank=True, db_index=True, max_length=12)),
                ('email_key', models.CharField(blank=True, db_index=True, max_length=254)),
                ('whatsapp_at', models.DateTimeField(blank=True, null=True)),
                ('email_at', models.DateTimeField(blank=True, null=True)),
                ('call_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='dashboard.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call')], max_length=10)),
                ('automatic', models.BooleanField(default=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(blank=True, choices=[('interested', 'Interested'), ('follow_up', 'Follow-up'), ('quotation', 'Quotation requested'), ('no_answer', 'No answer'), ('not_interested', 'Not interested')], max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.lead')),
                ('outbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.outboundmessage')),
            ],
            options={
                'ordering': ('-at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True, help_text='What the manager wants from this sheet.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sheets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='dashboard.leadsheet'),
        ),
    ]
