# Generated by Django 5.2.17 on 2026-10-10 19:08

from django.db import migrations, models


def outreach_from_contacts(apps, schema_editor):
    """Everything part 1 recorded was the Sales person reaching out (a message sent, a call): it is the last outreach too."""
    Lead = apps.get_model("dashboard", "Lead")
    Lead.objects.filter(last_contact_at__isnull=False).update(last_outreach_at=models.F("last_contact_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_b2b_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_outreach_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='incoming',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(outreach_from_contacts, migrations.RunPython.noop),
    ]
