# Generated by Django 5.2.17 on 2026-10-10 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def owners_from_sheets(apps, schema_editor):
    """What was recorded before part 3 counts for the Sales person who holds the company now: nobody had moved one yet."""
    LeadActivity = apps.get_model("dashboard", "LeadActivity")
    for row in LeadActivity.objects.filter(owner__isnull=True).select_related("lead__sheet"):
        row.owner_id = row.lead.sheet.assigned_to_id
        row.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_b2b_follow_ups'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='follow_up_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New lead'), ('email_sent', 'Email sent'), ('follow_up_1', 'Follow-up 1'), ('follow_up_2', 'Follow-up 2'), ('meeting', 'Meeting scheduled'), ('proposal', 'Proposal / rate sheet sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], max_length=12),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='kind',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call'), ('status', 'Stage changed')], max_length=10),
        ),
        migrations.RunPython(owners_from_sheets, migrations.RunPython.noop),
    ]
