# Generated by Django 5.2.17 on 2026-10-10 20:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_b2b_kpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='kind',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call'), ('status', 'Stage changed'), ('quotation', 'Quotation')], max_length=10),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('source_lang', models.CharField(max_length=40)),
                ('target_lang', models.CharField(max_length=40)),
                ('service', models.CharField(choices=[('translation', 'Translation'), ('review', 'Proofreading / review'), ('certified', 'Certified translation'), ('localization', 'Localization'), ('transcription', 'Transcription'), ('dtp', 'DTP'), ('interpreting', 'Interpreting'), ('other', 'Other')], default='translation', max_length=16)),
                ('unit', models.CharField(choices=[('words', 'Words'), ('pages', 'Pages'), ('hours', 'Hours'), ('project', 'Whole project')], default='words', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='How many words / pages / hours (1 for a whole project).')),
                ('rate', models.DecimalField(decimal_places=4, help_text='The price of one unit.', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('EGP', 'EGP'), ('SAR', 'SAR'), ('AED', 'AED')], default='USD', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='dashboard.lead')),
                ('outbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.outboundmessage')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='dashboard.task')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.quotation'),
        ),
    ]
